### ISSUE TITLE
[0.1.0] Login/Logout

### ISSUE THREAD

**Issue by soasme** [soasme/geetea#4]
- [x] service: be able to open a new window and then authenticate google account #1 #3 ;
- [x] service: be able to get/save/delete/validate google session #8 ;
- [x] service: be able to get google cookies #5  ; 
- [ ] service: authorization service: get cookies from localStorage or googleCloud #9  .
- [ ] view: landing page (with a login button)
- [ ] view: ui flow after authenticated success
- [ ] view: settings page (with a logout button)
- [ ] controller: integrate auth service and landing page
- [ ] controller: integrate session service and setting page
